#!/usr/bin/env python3

# Load modules from $CHARM_DIR/lib
import sys
sys.path.append('lib')

from charms.reactive import (
    main,
    set_state,
    remove_state,
    bus,
)

from charmhelpers.core.hookenv import action_fail


set_state('health.report')
states = bus.get_states().keys()

try:
    main()
except Exception as e:
    action_fail(str(e))
finally:
    remove_state('health.report')
